# Generated by Django 3.0.3 on 2020-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFiles',
            fields=[
                ('kind', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('createdTime', models.DateTimeField()),
                ('modifiedTime', models.DateTimeField()),
                ('mimeType', models.CharField(max_length=100)),
            ],
        ),
    ]
